fix stop

diff --git a/net-nntp/sabnzbd/files/sabnzbd.init b/net-nntp/sabnzbd/files/sabnzbd.init
--- a/net-nntp/sabnzbd/files/sabnzbd.init
+++ b/net-nntp/sabnzbd/files/sabnzbd.init
@@ -11,42 +11,44 @@ depend() {
 }
 
 start() {
-    ebegin "Starting SABnzbd"
-    if ! check_config ; then
-        eend 1
-        return 1
-    fi
-
-    start-stop-daemon --quiet --start -c ${SAB_USER}:${SAB_GROUP} \
+	ebegin "Starting SABnzbd"
+	if ! check_config ; then
+		eend 1
+		return 1
+	fi
+	export SABNZBD_CONFIG
+	start-stop-daemon --quiet --start -c ${SABNZBD_USER}:${SABNZBD_GROUP} \
         --exec /usr/bin/SABnzbd -- \
-        -s ${SAB_HOSTNAME}:${SAB_PORT} -f ${SAB_CONFIGFILE} -d &> /dev/null
-    eend $?
+        -s ${SABNZBD_HOSTNAME}:${SABNZBD_PORT} -d &> /dev/null
+	eend $?
 }
 
 stop() {
-    ebegin "Stopping SABnzbd"
-	if [[ -n $SAB_APIKEY ]];then
-	    URL="http://${SAB_HOSTNAME}:${SAB_PORT}/shutdown?session=$SAB_APIKEY"
+	ebegin "Stopping SABnzbd"
+	if [[ -n $SABNZBD_APIKEY ]];then
+		URL="http://${SABNZBD_HOSTNAME}:${SABNZBD_PORT}/shutdown?session=$SABNZBD_APIKEY"
 	else
-		URL="http://${SAB_HOSTNAME}:${SAB_PORT}/shutdown"
+		URL="http://${SABNZBD_HOSTNAME}:${SABNZBD_PORT}/shutdown"
 	fi
 	ewarn "Remote stop url is : $URL"
-    if [ -x /usr/bin/wget ] ; then
-		/usr/bin/wget -q --delete-after "${URL}"
-    elif [ -x /usr/bin/curl ] ; then
+	if [ -x /usr/bin/wget ] ; then
+		/usr/bin/wget  --http-user="$SABNZBD_HTTPUSER" --http-password="$SABNZBD_PASSWORD" -q --delete-after "${URL}"
+	elif [ -x /usr/bin/curl ] ; then
 		/usr/bin/curl --silent "${URL}" > /dev/null 2> /dev/null
 	fi
 	ewarn "Waiting for shutdown"
 	sleep 10
 	start-stop-daemon --quiet --stop --name SABnzbd.py
-    eend $?
+	eend $?
 }
 
 check_config() {
-    if [ ! -e ${SAB_CONFIGFILE} ] ; then
-        eerror "ERROR: can't find ${SAB_CONFIGFILE}."
-        return 1
-    else
-        return 0
-    fi
+	if [ ! -e ${SABNZBD_CONFIG} ] ; then
+		eerror "ERROR: can't find ${SABNZBD_CONFIG}."
+		return 1
+	else
+		return 0
+	fi
 }
+
+#vim:set et:
